on:
  workflow_dispatch:

name: Release

jobs:
  check:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
